apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hoplite_backend-poi-backend-app-dev
  annotations:
    argocd/app-name: hoplite_backend-poi-backend-app-dev
    backstage.io/kubernetes-id: hoplite_backend-poi-backend-app
    backstage.io/kubernetes-namespace: hoplite_backend
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/hoplite_backend-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/hoplite_backend/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/hoplite_backend/deployments/hoplite_backend-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/hoplite_backend-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/hoplite"
  system: workshop-system-hoplite_backend
  providesApis:
    - backend-api-hoplite_backend
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hoplite_backend
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/hoplite"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-hoplite_backend
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://hoplite_backend-poi-backend-app-hoplite_backend.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh23-demo/hoplite_backend-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/hoplite"
  system: workshop-system-hoplite_backend
  definition:
    $text: https://github.com/rhdh23-demo/hoplite_backend-backend/tree/main/src/main/resources/META-INF/openapi.yaml
